[package]
name = "pattern"
version = "0.1.0"
edition = "2024"
author = "Jorge Cata√±o <jorgeenriquecatano@gmail.com>"
description = "A pattern matching library for detect PII"
license = "MIT"

[dependencies]
regex = "1.11.1"
